version: '3.7'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
      args:
        VERSION: ${APP_VERSION}  # Pass version to Dockerfile
        ENVIRONMENT: ${APP_ENV}  # Pass environment to Dockerfile
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}"
    depends_on:
      - db
    ports:
      - "5001:5000"
    command: >
      bash -c "
      while !</dev/tcp/db/5432; do
        echo 'Waiting for database...';
        sleep 2;
      done;
      flask db upgrade &&
      flask run --host=0.0.0.0"

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
      args:
        VERSION: ${APP_VERSION}  # Pass version to Dockerfile
    environment:
      APP_VERSION: ${APP_VERSION}  # Specify the version
    ports:
      - "3000:3000"

volumes:
  postgres_data: