version: '3.7'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
      args:
        VERSION: ${APP_VERSION}
        ENVIRONMENT: ${APP_ENV}
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    ports:
      - "5001:5000"
    command: >
      bash -c "
      while !</dev/tcp/db/5432; do
        echo 'Waiting for database...';
        sleep 2;
      done;
      flask db upgrade &&
      flask run --host=0.0.0.0"

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
      args:
        VERSION: ${APP_VERSION}
    environment:
      APP_VERSION: ${APP_VERSION}
    ports:
      - "3000:3000"

# Remove the persistent volume for ephemeral data in development
# volumes:
#   postgres_data: