version: '3.7'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: mydemoappuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydemoapp_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://mydemoappuser:password@db:5432/mydemoapp_db"
    depends_on:
      - db
    ports:
      - "5001:5000"
    command: >
      bash -c "
      while !</dev/tcp/db/5432; do
        echo 'Waiting for database...';
        sleep 2;
      done;
      flask db upgrade &&
      flask run --host=0.0.0.0"

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

volumes:
  postgres_data: