apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-demo-app-backend
  labels:
    app: my-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-demo-app-backend
  template:
    metadata:
      labels:
        app: my-demo-app-backend
    spec:
      containers:
      - name: backend
        image: quay.io/rh-ee-pleathen/my-demo-app-backend:v0.2.0-dev
        ports:
        - containerPort: 5000
        env:
        - name: APP_ENV
          value: "production"
        - name: APP_VERSION
          value: "0.2.0-dev"
        - name: DATABASE_URL
          value: "postgresql://mydemoappuser:<password>@my-demo-app-db:5432/mydemoapp_db"
          valueFrom:
            secretKeyRef:
              name: my-demo-app-secrets
              key: DATABASE_URL