apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
  namespace: my-demo-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/backend"  # The directory created on the host
  storageClassName: manual