apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-demo-app-db
  namespace: my-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-demo-app-db
  template:
    metadata:
      labels:
        app: my-demo-app-db
    spec:
      containers:
      - name: postgres
        image: postgres:14
        env:
        - name: POSTGRES_USER
          value: mydemoappuser
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-db-secret
              key: MY_DEMO_APP_DB_PASSWORD
        - name: POSTGRES_DB
          value: mydemoapp_db
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data  # This is where PostgreSQL expects its data
      initContainers:
      - name: init-permissions
        image: busybox
        command: ['sh', '-c', 'chown -R 1000720000:1000720000 /var/lib/postgresql/data']
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc