apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: my-demo-app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Ti
  hostPath:
    path: "/mnt/data/postgres"  # This is the host path you created