apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: my-demo-app
spec:
  selector:
    app: my-demo-app
    tier: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP